### ISSUE TITLE
Records Not Being Deleted

### ISSUE THREAD

**Issue by bletherskite** [singer-io/tap-harvest-forecast#3] opened 2018-11-11 13:04 UTC
Hi there, I am using your Forecast integration in Stitch and I like it very much although I am having one issue. Forecast is a resource planning tool so there will be lots of additions and deletions over time. When I add a task its gets pulled through into the target db no problem (Postgresql in AWS), but when I delete a task it does not get deleted during the next sync. Am I missing something or is this the way its supposed to behave?

**Comment by timvisher** [comment] 2018-11-12 19:17
Short answer is that this is behaving as intended. You can read more at the [Stitch Docs](https://www.stitchdata.com/docs/replication/deleted-record-handling).

That said, if the API provides some way to retrieve deletes as soft deletes or otherwise it may be possible to enhance the tap to retrieve them.

Any ideas whether that's the case or not?

**Comment by timvisher** [comment] 2018-11-13 20:52
Going to close this out. Feel free to reopen if there's a chance that we could get soft deletes from the API>

**Closed as completed by timvisher** 2018-11-13 20:52 UTC
Labels: question

**Comment by bletherskite** [comment] 2018-11-13 20:57
Tim,, apologies for the delay in replying.  I guess the ball is in the Stitch court and they have as good as said that they won't be doing anything about it. Never mind. I will have to re-think my approach. Anyway, thanks for getting back to me and best wishes for the future.

**Comment by timvisher** [comment] 2018-11-14 14:03
No problem. FWIW there's really nothing Stitch or Singer can do in this case. The problem is the API not the tech.

Good luck! :)
